sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yuan0714
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t6S1vnm6oh5Pjmpkwnp
    access-key-secret: fVDd2c6VJyIxcYt5SvIIlj6U9q0OPx
    bucket-name: sky-take-out-rushen
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxbc69862b9645be06
    secret: 3641307c3957eda3c529ae7feac8b906
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    notifyUrl: https://5fc14795.r20.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://5fc14795.r20.cpolar.top/notify/refundSuccess
